// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.gecko.driver", "Firefox/geckodriver-win64.exe");
System.setProperty("webdriver.firefox.logfile", "/dev/null");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void signUpPage() {
    driver.get("https://rotten-apples.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.linkText("Register")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("main-holder"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void returnToHomePageLogin() {
    driver.get("https://rotten-apples.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.linkText("Log In")).click();
    driver.findElement(By.linkText("Rotten Apples")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(@href, \'/playlists\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void returnToHomePageRegister() {
    driver.get("https://rotten-apples.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.linkText("Register")).click();
    driver.findElement(By.linkText("Rotten Apples")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(@href, \'/playlists\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void loginPage() {
    driver.get("https://rotten-apples.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.linkText("Log In")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//main[@id=\'main-holder\']"));
      assert(elements.size() > 0);
    }
  }

  @Test
  public void allPlaylistCreate() {
    driver.get("https://rotten-apples.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.linkText("All Playlists")).click();
    driver.findElement(By.name("movieId")).click();
    {
      WebElement dropdown = driver.findElement(By.name("movieId"));
      dropdown.findElement(By.xpath("//option[. = '8 Seconds']")).click();
    }
    driver.findElement(By.cssSelector(".card:nth-child(1) option:nth-child(11)")).click();
    driver.findElement(By.cssSelector(".card:nth-child(1) input")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".text:nth-child(6) .moviePoster"));
      assert(elements.size() > 0);
    }
  }
}
